name: minizivpn

description: Modern UDP VPN Android App

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
