name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Clean old platforms
        run: |
          rm -rf android
          rm -rf ios
          rm -rf linux
          rm -rf macos
          rm -rf windows

      - name: Generate Flutter Structure
        run: flutter create . --project-name zivpn

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: MiniZiVPN
          path: build/app/outputs/flutter-apk/app-release.apk
